apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.image.repoCredsSecretName }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}/demosite:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
          - containerPort: 80
        env:
          - name: BIKES_SERVICE_URI
            value: http://{{ .Release.Name }}-contoso-bikerental-bikes
        resources:
{{ toYaml .Values.resources | indent 12 }}
